service: comosus-serverless
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

functions:
  sendEmail:
    handler: functions/sendEmail/index.sendEmail
    events:
      - httpApi:
          path: /send-email
          method: post
  uploadFile:
    handler: functions/uploadFile/index.uploadFile
    events:
      - http:
          path: /file-upload
          method: post
          cors: true
    environment:
      BUCKET: file-upload-bucket-comosus2

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: file-upload-bucket-comosus2
        AccessControl: PublicRead

plugins:
  - serverless-plugin-typescript
