service: comosus-serverless
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2

functions:
  sendEmail:
    handler: functions/sendEmail/index.sendEmail
    events:
      - httpApi:
          path: /send-email
          method: post
  getGitHubOrgInfo:
    handler: functions/getGitHubOrgInfo/index.handler
    events:
      - httpApi:
          path: /github-info
          method: get

plugins:
  - serverless-plugin-typescript
