service: comosus-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
