service: comosus-serverless
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2

functions:
  send-email:
    handler: functions/sendEmail/index.sendEmail
    events:
      - httpApi:
          path: /send-email
          method: post

  get-project-info:
    handler: functions/getProjectInfo/index.handler
    environment:
      GITHUB_PAT: some value
    events:
      - httpApi:
          path: /project-info
          method: get

plugins:
  - serverless-plugin-typescript
