service: comosus-serverless
frameworkVersion: "3"
useDotenv: true

params:
  prod:
    bucket-suffix: prod
  dev:
    bucket-suffix: dev

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-southeast-2
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

functions:
  send-email:
    handler: functions/sendEmail/index.sendEmail
    events:
      - httpApi:
          path: /send-email
          method: post
    environment:
      SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}

  uploadFile:
    handler: functions/uploadFile/index.uploadFile
    events:
      - httpApi:
          path: /file-upload
          method: post
    environment:
      BUCKET: file-upload-bucket-acomosus

  deleteFile:
    handler: functions/deleteFile/index.deleteFile
    events:
      - httpApi:
          path: /file-upload
          method: delete
    environment:
      BUCKET: file-upload-bucket-acomosus

  get-project-info:
    handler: functions/getProjectInfo/index.handler
    environment:
      GITHUB_PAT: ${env:GITHUB_PAT}
    events:
      - httpApi:
          path: /project-info
          method: get

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: a-comosus-avatar-bucket-${param:bucket-suffix}
        AccessControl: PublicRead

plugins:
  - serverless-plugin-typescript
